name: workflow-2
on:
  push:
    branches:
      - "main"
    paths-ignore:
      - ".github/workflows/*"
  issues:
    types: [opened, edited, closed]
jobs:
  details:
    runs-on: ubuntu-latest
    steps:
      - name: details
        run: echo "${{ toJSON(github.event) }}"
